### ISSUE TITLE
Remover caractere de espaço

### ISSUE THREAD

**Issue by mpdiasrosa** [Ldiasr18/rockPaperScissors#1]
Quando eu digito " rock" ou "rock " o programa está retornando que a entrada é inválida. Seria legal remover o caracter de espaço quando for fazer a validação.

**Evidência**
![image](https://github.com/Ldiasr18/rockPaperScissors/assets/56452943/22b296b7-2a97-4bfd-a375-49ebf65f92b6)
![image](https://github.com/Ldiasr18/rockPaperScissors/assets/56452943/601c4236-8eb8-4475-b66b-fddcc09cc27a)

**Comment by Ldiasr18** [comment]
Correção feita, agradecido.
